### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RetSamys**
Improved ligatures, latin input now coexists peacefully with UCSUR, added ligature support for space, cartouches, extentions, variants, cartouche middot, cartouche colon, manual control characters for cartouche and extension lines, and glyph combinations. Fixed space overlap between ligatures.

Made some quirky additions: te, to, aa, aaa, alternate cartouche brackets, extended a glyph, extended nasa glyph, directional ni, merged glyph of seme and a, alternate pana glyph

Guide for ligatures:

- ideographic space can be done with `  ` (double space) or `zz`
- cartouches get opened with `[` and closed with `]`
- cartouche colon is `:`
- cartouche interpunct is `.`
- manual lines are `_` for character extensions and `__` for cartouches (unless you want to do some fancy editing or opentype autocartouching isn't available, these shouldn't be necessary)
- character extensions get opened with `(` and closed with `)`
- scaled glyph combinations are done with `+`
- stacked glyph combinations are done with `-`
- directional ni can be done by adding `>` `^` `<` `v` and combinations thereof to `ni`
- variants are done by adding `#1` `#2` `#3` or `#4`

I also renamed the font to "nasin nanpa asuki" so it can be found better in my files and in Linku

### CODE REVIEW

**Comment by ETBCOR** [comment]
Oh my goodness, pona a!! These look like some great changes! Is this branch ready to merge? Then come spring break I'll release it as a new official version, if that sounds good!

**Comment by RetSamys** [comment]
Yep, this is all ready! The only thing I can think of changing is:

- limiting which words can be used as a base for scaling combination
- improving how the scaling combinations work

But both of these are more work, so I don't think I'll do these in the near future

**Comment by ETBCOR** [comment]
Hey, what changes have you been making? Should I merge your branch to main?

**Comment by ETBCOR** [comment]
Also, I just noticed that it looks like you've only been updating the .otf file. Do you mind uploading the newest .sfd file too?

**Comment by ETBCOR** [comment]
Thanks again for continuing work on this project!

**Pull request merged**
